---
title: "ANZ Task 2 - Predictive Analytics"
author: "Rinaldo Gagiano"
date: "20/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(readxl)
library(readr)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(corrplot)
library(lsr)
library(ggpubr)
library(tidyverse)
library(rpart)
library(car)
library(DAAG)
```

## Data Import and Subsetting

```{r, echo=TRUE,include=TRUE,warning=FALSE,message=FALSE}
anz <- read_xlsx("ANZ.xlsx") #Import
anz <- anz[,c(-3:-6,-8,-9,-19:-23)] #Irrelevant column Removal
```

```{r , echo=TRUE,include=TRUE,warning=FALSE,message=FALSE}
#Age, Gender and Annual Salary of each customer
salary <- anz %>% 
  filter(txn_description=="PAY/SALARY") %>%
  group_by(first_name) %>%
  summarise(age = max(age),
            gender = max(gender),
            "salary" = (sum(amount)*4))

#Most assigned merchant suberb, merchant state, and txn description per customer
salary2 <- anz %>%
  filter(!txn_description=="PAY/SALARY") %>%
  group_by(first_name) %>%
  summarise(most_suberb = head(names(sort(table(merchant_suburb),decreasing=TRUE)),1),
            most_state = head(names(sort(table(merchant_state),decreasing=TRUE)),1),
            most_txn = head(names(sort(table(txn_description),decreasing=TRUE)),1))

#Balance info for each customer
salary3 <- anz %>%
  group_by(first_name)%>%
  arrange(extraction) %>%
  summarise("initial balance" = head(balance,1),
            "final balance" = tail(balance,1))
salary3 <- salary3 %>% mutate("overall balance change" = `final balance`-`initial balance`)

#Creation of new dataframe
ann_sal <- inner_join(salary3,salary2, by = 'first_name')
ann_sal <- inner_join(ann_sal,salary, by = 'first_name')
ann_sal <- ann_sal[,-1] #Removal of first names
```

\pagebreak

## Model matrix Creation

```{r, include=TRUE,echo=TRUE}
suberb <- data.frame(model.matrix(~most_suberb+0, data = ann_sal))
state <- data.frame(model.matrix(~most_state+0, data = ann_sal))
txn <- data.frame(model.matrix(~most_txn+0, data = ann_sal))

total_sal_anz <- ann_sal[,c(-4:-6)]
total_sal_anz$gender <- ifelse(total_sal_anz$gender=="M",1,0)
total_sal_anz <- cbind(total_sal_anz,suberb,state,txn)
```

## Scatter Plots

```{r, include=TRUE,echo=FALSE}
par(mfrow=c(2, 2))
ggscatter(total_sal_anz, x = "age", y = "salary", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Customer Age", ylab = "Annual Salary")

ggscatter(total_sal_anz, x = "initial balance", y = "salary", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Customer Initial Balance", ylab = "Annual Salary")

ggscatter(total_sal_anz, x = "final balance", y = "salary", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Customer Final Balance", ylab = "Annual Salary")

ggscatter(total_sal_anz, x = "overall balance change", y = "salary", 
          add = "reg.line", conf.int = TRUE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Overall Change in Balance", ylab = "Annual Salary")
```

\pagebreak

## Linear Regression Model on Train and Test data

```{r, echo=TRUE,warning=FALSE,message=FALSE}
# Create Training and Test data -
set.seed(100)  # setting seed to reproduce results of random sampling
trainingRowIndex <- sample(1:nrow(total_sal_anz), 0.8*nrow(total_sal_anz))  # row indices for training data
train_x <- total_sal_anz[trainingRowIndex, ]  # model training data
test_x  <- total_sal_anz[-trainingRowIndex, ]   # test data

lrmodel <- lm(salary ~. , data = train_x)# build the model
salPred <- predict(lrmodel, test_x)  # predict salary

#prediction accuracy and error rates
actuals_preds <- data.frame(cbind(actuals=test_x$salary, predicteds=salPred))  # make actuals_predicteds dataframe.
correlation_accuracy <- cor(actuals_preds)  # 18.25%
paste0("Prediction Accuracy ",round(correlation_accuracy[1,2]*100,2),"%")
```

```{r, include=TRUE,echo=FALSE}
paste("Not very good at all but still happy for my first attempt :)")
```

```{r , include=TRUE,echo=TRUE}
min_max_accuracy <- mean(apply(actuals_preds, 1, min) / apply(actuals_preds, 1, max))  
paste0("Min Max Accuracy ",round(min_max_accuracy*100,2),"%")

mape <- mean(abs((actuals_preds$predicteds - actuals_preds$actuals))/actuals_preds$actuals)  
paste0("Mean Absolute Percentage Deviation ",round(mape*100,2),"%")
```

\pagebreak

## Decision TREE

```{r , echo=TRUE}
anztree <- rpart(salary ~. ,data=total_sal_anz,method="anova")

plot(anztree,margin=0.1)
text(anztree,cex=.8)

plotcp(anztree)
```




















































